"""add error table

Revision ID: 46f816ae9a84
Revises: 5acebfd7178b
Create Date: 2022-07-21 05:14:23.571110

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '46f816ae9a84'
down_revision = '5acebfd7178b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('API Error',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('function', sa.String(), nullable=True),
    sa.Column('traceback', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_API Error_function'), 'API Error', ['function'], unique=False)
    op.create_index(op.f('ix_API Error_id'), 'API Error', ['id'], unique=False)
    op.drop_index('ix_forms_text', table_name='forms')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_forms_text', 'forms', ['text'], unique=False)
    op.drop_index(op.f('ix_API Error_id'), table_name='API Error')
    op.drop_index(op.f('ix_API Error_function'), table_name='API Error')
    op.drop_table('API Error')
    # ### end Alembic commands ###
